#!/bin/sh

set -e

if [ "$1" = configure ]; then
    # Try to setcap or fall back to setuid.
    # The specific setcap invocations also need to be whitelisted to make the
    # build pass (in debian/meta/setcap.yaml as a nested array of argument
    # arrays).
    if command -v setcap > /dev/null; then
        cap="CAP_SYS_NICE=+ep"
        path="/usr/bin/kwin_wayland"
        if setcap $cap $path; then
            echo "Setcap worked for $path!"
        else
            echo "Setcap failed for $path
        fi
    else
        echo "Setcap is not installed" >&2
    fi
fi

#DEBHELPER#

exit 0
